plugins {
    id 'com.android.application'
}
android {
    namespace 'com.vsmanager'
    compileSdk 34
    defaultConfig {
        applicationId "com.vsmanager"
        minSdk 31
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
dependencies {
    implementation 'moe.shizuku.manager:api:13.1.5'
    implementation 'moe.shizuku.manager:shizuku:13.1.5'
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
